// libs/braid-angular/src/lib/guest.ts
import { ApplicationRef, createComponent, type EnvironmentProviders, type Type } from '@angular/core';
import { createApplication } from '@angular/platform-browser';
import { defineFragment, type FragmentEnv, type FragmentContract } from '@braidlabs/core';

/**
 * The Angular guest binding: a contract-mode fragment.
 *
 * ```ts
 * // main.ts — the fragment's entry module
 * import { defineAngularFragment } from '@braidlabs/angular';
 * import { App } from './app';
 *
 * defineAngularFragment({
 *   component: App,
 *   contract: { version: '1.0.0' },
 *   providers: (env) => [provideRouter(routes), { provide: BASE_PATH, useValue: env.location.basePath }],
 * });
 * ```
 *
 * `createApplication()` rather than `bootstrapApplication()`, because the fragment does not own a
 * document element to bootstrap into — it owns `env.root`, inside the host's shadow tree. The
 * component is created explicitly and attached to the application's view tree, which is the same
 * thing bootstrap does with one fewer assumption about where the page came from.
 *
 * **What this is not doing, and why that matters.** No `DOCUMENT` token override, no zone patching
 * concerns, no router history virtualisation. In compat mode Angular believes it owns the browser
 * and Braid spends considerable machinery keeping that belief true — the document facade, the
 * history interception, the singleton renaming, the whole catalogue in `braid-failure-modes.md`. A
 * contract fragment is told the truth instead, and none of that code runs.
 */

export interface AngularFragmentOptions<T> {
  component: Type<T>;
  contract?: FragmentContract;
  /** Application-level providers. Receives the env so routing can be bound to `env.location`. */
  providers?(env: FragmentEnv): Array<EnvironmentProviders | unknown>;
}

export function defineAngularFragment<T>(options: AngularFragmentOptions<T>): void {
  defineFragment({
    ...(options.contract === undefined ? {} : { contract: options.contract }),
    async mount(env: FragmentEnv) {
      const app: ApplicationRef = await createApplication({
        providers: (options.providers?.(env) ?? []) as never,
      });

      const component = createComponent(options.component, {
        environmentInjector: app.injector,
        hostElement: env.root,
      });
      app.attachView(component.hostView);

      /**
       * Destroyed on `signal`, which fires only after every `onClosing` handler has settled — so a
       * service flushing an outbox in `onClosing` still has its injector when it runs.
       */
      env.signal.addEventListener(
        'abort',
        () => {
          component.destroy();
          app.destroy();
        },
        { once: true },
      );
    },
  });
}

// libs/braid-react/src/lib/guest.ts
import { createElement, type ReactNode } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { defineFragment, type FragmentEnv, type FragmentContract } from '@braidlabs/core';

/**
 * The React guest binding: a contract-mode fragment, in about as much code as it should take.
 *
 * ```tsx
 * // main.tsx — the fragment's entry module
 * import { defineReactFragment } from '@braidlabs/react';
 * import { App } from './app';
 *
 * defineReactFragment({
 *   contract: { version: '1.0.0' },
 *   render: (env) => <App basePath={env.location.basePath} />,
 * });
 * ```
 *
 * Note there is no `document`, no `window` patching and no router adapter here. That is the point of
 * contract mode: the fragment renders into `env.root`, learns its base path from `env.location`, and
 * unmounts on `env.signal`. Everything compat mode has to manufacture, this simply does not need.
 *
 * Router integration is deliberately left to the application. React has no single router, and a
 * binding that picked one would be wrong for most fragments — `env.location` and `env.history` are
 * the two things any of them can be configured from, and they are on the env the render function
 * receives.
 */

export interface ReactFragmentOptions {
  contract?: FragmentContract;
  /** Renders the fragment's tree. Re-invoked when the host changes props. */
  render(env: FragmentEnv): ReactNode;
}

export function defineReactFragment(options: ReactFragmentOptions): void {
  defineFragment({
    ...(options.contract === undefined ? {} : { contract: options.contract }),
    mount(env: FragmentEnv) {
      const root: Root = createRoot(env.root);
      root.render(createElement(Wrapper, { env, render: options.render }));

      /**
       * Unmounted on `signal`, which fires only after every `onClosing` handler has settled. A
       * React tree torn down before its effects have flushed is how an in-flight save becomes a
       * "setState on an unmounted component" warning and a lost write.
       */
      env.signal.addEventListener('abort', () => root.unmount(), { once: true });

      // Props changes re-render rather than remount: a remount would discard component state the
      // user is looking at, which is the wrong response to a prop the host adjusted.
      env.onPropsChanged(() => root.render(createElement(Wrapper, { env, render: options.render })));
    },
  });
}

function Wrapper({ env, render }: { env: FragmentEnv; render: (env: FragmentEnv) => ReactNode }): ReactNode {
  return render(env);
}
